package com.arch.common.dao;


import com.arch.common.pojo.TlCostTravel;

import java.util.List;
import java.util.Map;
public interface TlCostTravelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_cost_travel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_cost_travel
     *
     * @mbggenerated
     */
    int insert(TlCostTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_cost_travel
     *
     * @mbggenerated
     */
    int insertSelective(TlCostTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_cost_travel
     *
     * @mbggenerated
     */
    TlCostTravel selectByPrimaryKey(Integer travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_cost_travel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TlCostTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tl_cost_travel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TlCostTravel record);

    List<TlCostTravel> selectByPageBean(Map<String, Object> paraMap);

    Integer selectRowForPageBean(Map<String, Object> paraMap);
}