package com.test.admin.admin.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TlCostTravel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_id
     *
     * @mbggenerated
     */
    private Integer travelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.dept_id
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_site
     *
     * @mbggenerated
     */
    private String travelSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_start_time
     *
     * @mbggenerated
     */
    private Date travelStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_back_time
     *
     * @mbggenerated
     */
    private Date travelBackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_person_count
     *
     * @mbggenerated
     */
    private Integer travelPersonCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_person_name
     *
     * @mbggenerated
     */
    private String travelPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_day_count
     *
     * @mbggenerated
     */
    private Integer travelDayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_amount
     *
     * @mbggenerated
     */
    private BigDecimal travelAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_reason
     *
     * @mbggenerated
     */
    private String travelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_remark
     *
     * @mbggenerated
     */
    private String travelRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.deal_status
     *
     * @mbggenerated
     */
    private Integer dealStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.enter_dept_id
     *
     * @mbggenerated
     */
    private Integer enterDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.enter_time
     *
     * @mbggenerated
     */
    private Date enterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_cost_travel.travel_mode
     *
     * @mbggenerated
     */
    private String travelMode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_id
     *
     * @return the value of tl_cost_travel.travel_id
     *
     * @mbggenerated
     */
    public Integer getTravelId() {
        return travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_id
     *
     * @param travelId the value for tl_cost_travel.travel_id
     *
     * @mbggenerated
     */
    public void setTravelId(Integer travelId) {
        this.travelId = travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.dept_id
     *
     * @return the value of tl_cost_travel.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.dept_id
     *
     * @param deptId the value for tl_cost_travel.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.dept_name
     *
     * @return the value of tl_cost_travel.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.dept_name
     *
     * @param deptName the value for tl_cost_travel.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_site
     *
     * @return the value of tl_cost_travel.travel_site
     *
     * @mbggenerated
     */
    public String getTravelSite() {
        return travelSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_site
     *
     * @param travelSite the value for tl_cost_travel.travel_site
     *
     * @mbggenerated
     */
    public void setTravelSite(String travelSite) {
        this.travelSite = travelSite == null ? null : travelSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_start_time
     *
     * @return the value of tl_cost_travel.travel_start_time
     *
     * @mbggenerated
     */
    public Date getTravelStartTime() {
        return travelStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_start_time
     *
     * @param travelStartTime the value for tl_cost_travel.travel_start_time
     *
     * @mbggenerated
     */
    public void setTravelStartTime(Date travelStartTime) {
        this.travelStartTime = travelStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_back_time
     *
     * @return the value of tl_cost_travel.travel_back_time
     *
     * @mbggenerated
     */
    public Date getTravelBackTime() {
        return travelBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_back_time
     *
     * @param travelBackTime the value for tl_cost_travel.travel_back_time
     *
     * @mbggenerated
     */
    public void setTravelBackTime(Date travelBackTime) {
        this.travelBackTime = travelBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_person_count
     *
     * @return the value of tl_cost_travel.travel_person_count
     *
     * @mbggenerated
     */
    public Integer getTravelPersonCount() {
        return travelPersonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_person_count
     *
     * @param travelPersonCount the value for tl_cost_travel.travel_person_count
     *
     * @mbggenerated
     */
    public void setTravelPersonCount(Integer travelPersonCount) {
        this.travelPersonCount = travelPersonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_person_name
     *
     * @return the value of tl_cost_travel.travel_person_name
     *
     * @mbggenerated
     */
    public String getTravelPersonName() {
        return travelPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_person_name
     *
     * @param travelPersonName the value for tl_cost_travel.travel_person_name
     *
     * @mbggenerated
     */
    public void setTravelPersonName(String travelPersonName) {
        this.travelPersonName = travelPersonName == null ? null : travelPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_day_count
     *
     * @return the value of tl_cost_travel.travel_day_count
     *
     * @mbggenerated
     */
    public Integer getTravelDayCount() {
        return travelDayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_day_count
     *
     * @param travelDayCount the value for tl_cost_travel.travel_day_count
     *
     * @mbggenerated
     */
    public void setTravelDayCount(Integer travelDayCount) {
        this.travelDayCount = travelDayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_amount
     *
     * @return the value of tl_cost_travel.travel_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTravelAmount() {
        return travelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_amount
     *
     * @param travelAmount the value for tl_cost_travel.travel_amount
     *
     * @mbggenerated
     */
    public void setTravelAmount(BigDecimal travelAmount) {
        this.travelAmount = travelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_reason
     *
     * @return the value of tl_cost_travel.travel_reason
     *
     * @mbggenerated
     */
    public String getTravelReason() {
        return travelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_reason
     *
     * @param travelReason the value for tl_cost_travel.travel_reason
     *
     * @mbggenerated
     */
    public void setTravelReason(String travelReason) {
        this.travelReason = travelReason == null ? null : travelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_remark
     *
     * @return the value of tl_cost_travel.travel_remark
     *
     * @mbggenerated
     */
    public String getTravelRemark() {
        return travelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_remark
     *
     * @param travelRemark the value for tl_cost_travel.travel_remark
     *
     * @mbggenerated
     */
    public void setTravelRemark(String travelRemark) {
        this.travelRemark = travelRemark == null ? null : travelRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.deal_status
     *
     * @return the value of tl_cost_travel.deal_status
     *
     * @mbggenerated
     */
    public Integer getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.deal_status
     *
     * @param dealStatus the value for tl_cost_travel.deal_status
     *
     * @mbggenerated
     */
    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.enter_dept_id
     *
     * @return the value of tl_cost_travel.enter_dept_id
     *
     * @mbggenerated
     */
    public Integer getEnterDeptId() {
        return enterDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.enter_dept_id
     *
     * @param enterDeptId the value for tl_cost_travel.enter_dept_id
     *
     * @mbggenerated
     */
    public void setEnterDeptId(Integer enterDeptId) {
        this.enterDeptId = enterDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.enter_time
     *
     * @return the value of tl_cost_travel.enter_time
     *
     * @mbggenerated
     */
    public Date getEnterTime() {
        return enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.enter_time
     *
     * @param enterTime the value for tl_cost_travel.enter_time
     *
     * @mbggenerated
     */
    public void setEnterTime(Date enterTime) {
        this.enterTime = enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_cost_travel.travel_mode
     *
     * @return the value of tl_cost_travel.travel_mode
     *
     * @mbggenerated
     */
    public String getTravelMode() {
        return travelMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_cost_travel.travel_mode
     *
     * @param travelMode the value for tl_cost_travel.travel_mode
     *
     * @mbggenerated
     */
    public void setTravelMode(String travelMode) {
        this.travelMode = travelMode == null ? null : travelMode.trim();
    }
}